export const ROOTS = {
  mainPage: '/mainPage',
  user: '/user',
  tasks: '/tasks',
  grade: '/grade',
  quickCount: '/quickCount',
  timetable: '/timetable',
  maze: '/maze',
  support: '/support',
  about: '/about',
  editingPages: '/editingPages',
  login: '/login',
  createAccount: '/createAccount',
  userManagement: '/userManagement',
  play: '/play',
};
